// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://tmkjtlbuglbgsylwcqie.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InRta2p0bGJ1Z2xiZ3N5bHdjcWllIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTA4NDEwNzUsImV4cCI6MjA2NjQxNzA3NX0.2mBrooJYLTpPguR82wxJxVU_On7PKKVvX1Ry67kxfmk";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);